import { CalendarDays, CheckCircle2, Clock3, FileText, Timer, Umbrella } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEmployeeDashboard } from '../../../hooks/useDashboard';
import { formatCurrency, formatDate, formatDisplayTime } from '../../../utils/formatters';

const Card = ({ icon: Icon, label, value, subtext, tone }: any) => <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div><div className={`h-fit rounded-xl p-3 ${tone}`}><Icon size={20} /></div></div><p className="mt-3 text-xs text-slate-500">{subtext}</p></div>;

const Dashboard = () => {
  const { data, isLoading, isError } = useEmployeeDashboard();
  if (isLoading) return <div className="p-6 text-sm text-slate-500">Loading your workday…</div>;
  if (isError || !data) return <div className="m-6 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">We could not load your dashboard. Please refresh or contact HR.</div>;
  const todayStatus = data.today?.timeOut ? 'Clocked out' : data.today?.timeIn ? 'Clocked in' : 'Not clocked in';
  const attendanceRate = data.month.attendance.length ? Math.round((data.month.attendanceDays / data.month.attendance.length) * 100) : 0;

  return <div className="min-h-full bg-slate-50 p-4 md:p-6">
    <div className="mb-6 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-sm font-semibold text-violet-600">EMPLOYEE PORTAL</p><h1 className="text-2xl font-bold text-slate-900">Welcome back, {data.employee.firstName}</h1><p className="mt-1 text-sm text-slate-500">Your schedule, attendance, leave balance, and pay updates in one place.</p></div><div className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-600">{data.employee.schedule ? `${data.employee.schedule.name}: ${data.employee.schedule.shiftStart}–${data.employee.schedule.shiftEnd}` : 'No schedule assigned'}</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={Clock3} label="Today" value={todayStatus} subtext={data.today?.timeIn ? `In: ${formatDisplayTime(data.today.timeIn)}${data.today.timeOut ? ` · Out: ${formatDisplayTime(data.today.timeOut)}` : ''}` : 'Use the attendance kiosk to clock in'} tone="bg-indigo-50 text-indigo-600"/><Card icon={CheckCircle2} label="Attendance days" value={data.month.attendanceDays} subtext={`${attendanceRate}% of logged workdays this month`} tone="bg-emerald-50 text-emerald-600"/><Card icon={Timer} label="Overtime" value={`${Math.floor(data.month.overtimeMinutes / 60)}h ${data.month.overtimeMinutes % 60}m`} subtext={`${data.month.lateMinutes} late minute(s) this month`} tone="bg-amber-50 text-amber-600"/><Card icon={Umbrella} label="Leave available" value={`${data.leave.available} days`} subtext={`${data.leave.used} used from ${data.leave.allocated} allocated`} tone="bg-violet-50 text-violet-600"/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-3"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">This month’s attendance</h2><p className="text-xs text-slate-500">Your latest attendance records</p></div><Link to="/portal/attendance" className="text-xs font-semibold text-indigo-600 no-underline">View logs</Link></div><div className="mt-5 grid grid-cols-7 gap-2">{data.month.attendance.slice(-14).map((entry: any) => <div key={entry.day} className={`rounded-xl border p-2 text-center ${entry.status === 'LATE' ? 'border-amber-200 bg-amber-50' : entry.status === 'PRESENT' ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-slate-50'}`}><p className="text-[10px] font-bold text-slate-500">{entry.label}</p><p className="mt-1 text-xs font-bold text-slate-700">{new Date(entry.day).getUTCDate()}</p><p className="mt-1 text-[9px] font-semibold text-slate-500">{entry.status}</p></div>)}</div>{!data.month.attendance.length && <p className="py-8 text-center text-sm text-slate-500">No attendance records yet this month.</p>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Leave requests</h2><p className="text-xs text-slate-500">Recent filing status</p></div><Link to="/portal/leave" className="text-xs font-semibold text-indigo-600 no-underline">Manage leave</Link></div><div className="mt-4 space-y-3">{data.recentLeaves.length ? data.recentLeaves.map((leave: any) => <div key={leave.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="text-sm font-semibold text-slate-700">{leave.type} leave</p><p className="text-xs text-slate-500">{formatDate(leave.startDate)} · {leave.totalDays} day(s)</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${leave.status === 'APPROVED' ? 'bg-emerald-100 text-emerald-700' : leave.status === 'REJECTED' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'}`}>{leave.status}</span></div>) : <p className="py-6 text-center text-sm text-slate-500">No leave requests yet.</p>}</div></section></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Recent payslips</h2><p className="text-xs text-slate-500">Approved and paid payroll only</p></div><FileText className="text-violet-500" size={19}/></div><div className="mt-4 space-y-3">{data.payrolls.length ? data.payrolls.map((payroll: any) => <div key={payroll.id} className="flex items-center justify-between"><div><p className="text-sm font-medium text-slate-700">{formatDate(payroll.periodStart)} – {formatDate(payroll.periodEnd)}</p><p className="text-xs text-slate-500">{payroll.status}</p></div><b className="text-sm text-slate-800">{formatCurrency(payroll.netPay)}</b></div>) : <p className="py-6 text-center text-sm text-slate-500">No released payslips.</p>}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-3"><div className="flex items-center gap-2"><CalendarDays className="text-indigo-500" size={19}/><div><h2 className="font-bold text-slate-900">HR notifications</h2><p className="text-xs text-slate-500">The newest updates from your HR team</p></div></div><div className="mt-3 divide-y divide-slate-100">{data.notifications.length ? data.notifications.map((notification: any) => <div key={notification.id} className="py-3"><div className="flex items-center justify-between"><p className="text-sm font-semibold text-slate-700">{notification.title}</p>{!notification.isRead && <span className="h-2 w-2 rounded-full bg-indigo-500"/>}</div><p className="mt-1 text-xs text-slate-500">{notification.message}</p></div>) : <p className="py-6 text-center text-sm text-slate-500">You are all caught up.</p>}</div></section></div>
  </div>;
};
export default Dashboard;